import type {
  ActivityEvent,
  ChatMessage,
  DocumentItem,
  MessagePost,
  Milestone,
  Profile,
  Project,
  Todo,
  TodoComment,
  TodoList,
  TodoSubtask,
} from "@/lib/types";

export const profiles: Profile[] = [
  {
    id: "sam",
    fullName: "Sam Rivera",
    email: "sam@p11creative.com",
    initials: "SR",
    role: "admin",
    jobTitle: "Managing Director",
    active: true,
    isInternal: true,
    acceloStaffId: "101",
    slackUserId: "U01SAM",
  },
  {
    id: "maya",
    fullName: "Maya Chen",
    email: "maya@p11creative.com",
    initials: "MC",
    role: "manager",
    jobTitle: "Account Director",
    active: true,
    isInternal: true,
    acceloStaffId: "102",
  },
  {
    id: "alex",
    fullName: "Alex Brooks",
    email: "alex@p11creative.com",
    initials: "AB",
    role: "member",
    jobTitle: "Creative Lead",
    active: true,
    isInternal: true,
    acceloStaffId: "103",
  },
  {
    id: "jordan",
    fullName: "Jordan Lee",
    email: "jordan@p11creative.com",
    initials: "JL",
    role: "member",
    jobTitle: "Digital Strategist",
    active: true,
    isInternal: true,
    acceloStaffId: "104",
  },
  {
    id: "taylor",
    fullName: "Taylor Morgan",
    email: "taylor@p11creative.com",
    initials: "TM",
    role: "member",
    jobTitle: "Production Manager",
    active: true,
    isInternal: true,
    acceloStaffId: "105",
  },
];

export const projects: Project[] = [
  {
    id: "aster-house",
    name: "Aster House Launch",
    client: "Northline Residential",
    description:
      "Integrated brand launch for a 186-unit luxury apartment community, spanning digital, print, and leasing collateral.",
    status: "active",
    color: "bg-amber-500",
    acceloJobId: "81240",
    slackChannel: "#aster-house",
    progress: 68,
    updatedAt: "2026-08-07T15:25:00.000Z",
    memberIds: ["sam", "maya", "alex", "jordan", "taylor"],
  },
  {
    id: "the-rowan",
    name: "The Rowan Rebrand",
    client: "Sable Property Group",
    description:
      "Brand refresh, resident acquisition campaign, and property signage system for an established community.",
    status: "active",
    color: "bg-emerald-500",
    acceloJobId: "81304",
    slackChannel: "#the-rowan",
    progress: 42,
    updatedAt: "2026-08-07T14:10:00.000Z",
    memberIds: ["maya", "alex", "taylor"],
  },
  {
    id: "parkline-q3",
    name: "Parkline Q3 Campaign",
    client: "Brightstone Communities",
    description:
      "Paid media, social creative, and direct-mail campaign focused on late-summer occupancy.",
    status: "active",
    color: "bg-sky-500",
    acceloJobId: "81417",
    slackChannel: "#parkline-q3",
    progress: 77,
    updatedAt: "2026-08-06T21:40:00.000Z",
    memberIds: ["sam", "jordan", "taylor"],
  },
  {
    id: "juniper-yards",
    name: "Juniper Yards Signage",
    client: "Commonwell Development",
    description:
      "Wayfinding, monument, leasing office, and construction signage production program.",
    status: "on_hold",
    color: "bg-violet-500",
    acceloJobId: "80992",
    slackChannel: "#juniper-yards",
    progress: 31,
    updatedAt: "2026-08-04T18:30:00.000Z",
    memberIds: ["maya", "alex", "taylor"],
  },
];

export const todoLists: TodoList[] = [
  { id: "aster-launch", projectId: "aster-house", name: "Launch critical", position: 1 },
  { id: "aster-creative", projectId: "aster-house", name: "Creative production", position: 2 },
  { id: "rowan-brand", projectId: "the-rowan", name: "Brand system", position: 1 },
  { id: "parkline-media", projectId: "parkline-q3", name: "Campaign delivery", position: 1 },
  { id: "juniper-print", projectId: "juniper-yards", name: "Print production", position: 1 },
];

export const todos: Todo[] = [
  {
    id: "t1",
    projectId: "aster-house",
    listId: "aster-launch",
    title: "Approve launch media plan",
    description: "Final channel allocation and September flight dates.",
    assigneeId: "maya",
    assigneeIds: ["maya", "jordan", "alex"],
    completionSubscriberIds: ["sam", "taylor"],
    dueDate: "2026-08-07",
    status: "in_progress",
    priority: "high",
    acceloTaskId: "50121",
    updatedAt: "2026-08-07T15:25:00.000Z",
  },
  {
    id: "t2",
    projectId: "aster-house",
    listId: "aster-creative",
    title: "Finalize leasing brochure",
    assigneeId: "alex",
    dueDate: "2026-08-08",
    status: "in_progress",
    priority: "high",
    acceloTaskId: "50125",
    updatedAt: "2026-08-07T14:12:00.000Z",
  },
  {
    id: "t3",
    projectId: "aster-house",
    listId: "aster-creative",
    title: "Release exterior banners to print",
    assigneeId: "taylor",
    dueDate: "2026-08-10",
    status: "open",
    priority: "normal",
    acceloTaskId: "50129",
    updatedAt: "2026-08-06T19:00:00.000Z",
  },
  {
    id: "t4",
    projectId: "aster-house",
    listId: "aster-launch",
    title: "Configure conversion events",
    assigneeId: "jordan",
    dueDate: "2026-08-06",
    status: "blocked",
    priority: "high",
    acceloTaskId: "50132",
    updatedAt: "2026-08-07T11:02:00.000Z",
  },
  {
    id: "t5",
    projectId: "the-rowan",
    listId: "rowan-brand",
    title: "Present identity directions",
    assigneeId: "alex",
    dueDate: "2026-08-11",
    status: "in_progress",
    priority: "normal",
    acceloTaskId: "50214",
    updatedAt: "2026-08-07T13:12:00.000Z",
  },
  {
    id: "t6",
    projectId: "the-rowan",
    listId: "rowan-brand",
    title: "Confirm resident research findings",
    assigneeId: "maya",
    dueDate: "2026-08-09",
    status: "open",
    priority: "normal",
    acceloTaskId: "50217",
    updatedAt: "2026-08-06T20:31:00.000Z",
  },
  {
    id: "t7",
    projectId: "parkline-q3",
    listId: "parkline-media",
    title: "Launch paid social ad set",
    assigneeId: "jordan",
    dueDate: "2026-08-08",
    status: "in_progress",
    priority: "high",
    acceloTaskId: "50308",
    updatedAt: "2026-08-07T12:18:00.000Z",
  },
  {
    id: "t8",
    projectId: "parkline-q3",
    listId: "parkline-media",
    title: "Deliver direct-mail list to printer",
    assigneeId: "taylor",
    dueDate: "2026-08-12",
    status: "open",
    priority: "normal",
    acceloTaskId: "50313",
    updatedAt: "2026-08-07T09:24:00.000Z",
  },
  {
    id: "t9",
    projectId: "parkline-q3",
    listId: "parkline-media",
    title: "Review weekly lead quality",
    assigneeId: "sam",
    dueDate: "2026-08-07",
    status: "open",
    priority: "normal",
    acceloTaskId: "50317",
    updatedAt: "2026-08-06T23:04:00.000Z",
  },
  {
    id: "t10",
    projectId: "juniper-yards",
    listId: "juniper-print",
    title: "Resolve monument sign permit",
    assigneeId: "taylor",
    dueDate: "2026-08-05",
    status: "blocked",
    priority: "high",
    acceloTaskId: "49831",
    updatedAt: "2026-08-05T18:30:00.000Z",
  },
];

export const todoSubtasks: TodoSubtask[] = [
  {
    id: "st1",
    todoId: "t1",
    title: "Confirm tracking numbers by channel",
    position: 0,
    completedAt: "2026-08-06T16:20:00.000Z",
    completedBy: "jordan",
  },
  {
    id: "st2",
    todoId: "t1",
    title: "Consolidate internal review notes",
    position: 1,
  },
  {
    id: "st3",
    todoId: "t1",
    title: "Prepare client-ready deliverable",
    position: 2,
  },
];

export const todoComments: TodoComment[] = [
  {
    id: "tc1",
    todoId: "t1",
    authorId: "maya",
    body: "@Sam Can you confirm which tracking numbers should be used for paid social and YouTube?",
    createdAt: "2026-08-05T15:14:00.000Z",
    mentionedProfileIds: ["sam"],
    attachments: [],
  },
  {
    id: "tc2",
    todoId: "t1",
    authorId: "jordan",
    body: "The research, metadata, on-page, and technical tabs are ready for internal review.",
    createdAt: "2026-08-05T17:42:00.000Z",
    mentionedProfileIds: ["maya", "alex"],
    attachments: [
      {
        id: "tca1",
        title: "Working SEO workbook",
        externalUrl: "https://docs.google.com/spreadsheets/",
      },
    ],
  },
  {
    id: "tc3",
    todoId: "t1",
    authorId: "sam",
    body: "Let’s do a quick internal review, consolidate edits, then release one client-facing version.",
    createdAt: "2026-08-06T16:05:00.000Z",
    mentionedProfileIds: [],
    attachments: [],
  },
];

export const messagePosts: MessagePost[] = [
  {
    id: "m1",
    projectId: "aster-house",
    title: "Launch readiness — August 7",
    body: "Media is approved pending final conversion tracking. Print production is on schedule. Please flag anything that could move the launch date by noon tomorrow.",
    category: "update",
    authorId: "maya",
    createdAt: "2026-08-07T14:20:00.000Z",
    commentCount: 4,
  },
  {
    id: "m2",
    projectId: "aster-house",
    title: "Brochure proof round two",
    body: "The amenity spread and neighborhood map are updated. Round-two PDF is in Docs & Files for consolidated feedback.",
    category: "creative",
    authorId: "alex",
    createdAt: "2026-08-06T19:45:00.000Z",
    commentCount: 7,
  },
  {
    id: "m3",
    projectId: "the-rowan",
    title: "Positioning direction selected",
    body: "The client selected the warmer, editorial direction. We can move forward with the identity system and copy platform.",
    category: "decision",
    authorId: "maya",
    createdAt: "2026-08-07T11:10:00.000Z",
    commentCount: 2,
  },
];

export const chatMessages: ChatMessage[] = [
  {
    id: "c1",
    projectId: "aster-house",
    authorId: "jordan",
    body: "Conversion events are mapped. I’m waiting on GTM publish access.",
    createdAt: "2026-08-07T15:02:00.000Z",
  },
  {
    id: "c2",
    projectId: "aster-house",
    authorId: "maya",
    body: "I just nudged the client and added you to the access thread.",
    createdAt: "2026-08-07T15:05:00.000Z",
  },
  {
    id: "c3",
    projectId: "aster-house",
    authorId: "alex",
    body: "Round-three brochure export will be up before 4.",
    createdAt: "2026-08-07T15:08:00.000Z",
  },
];

export const documentItems: DocumentItem[] = [
  {
    id: "d1",
    projectId: "aster-house",
    title: "Aster House launch brief",
    kind: "doc",
    authorId: "maya",
    updatedAt: "2026-08-07T13:30:00.000Z",
  },
  {
    id: "d2",
    projectId: "aster-house",
    title: "Leasing_Brochure_R2.pdf",
    kind: "file",
    authorId: "alex",
    size: "18.4 MB",
    updatedAt: "2026-08-06T19:32:00.000Z",
  },
  {
    id: "d3",
    projectId: "aster-house",
    title: "Media_Plan_Final.xlsx",
    kind: "file",
    authorId: "jordan",
    size: "742 KB",
    updatedAt: "2026-08-07T10:14:00.000Z",
  },
];

export const milestones: Milestone[] = [
  {
    id: "mstone1",
    projectId: "aster-house",
    title: "Campaign go-live",
    dueDate: "2026-08-14",
    acceloMilestoneId: "9001",
  },
  {
    id: "mstone2",
    projectId: "the-rowan",
    title: "Identity approval",
    dueDate: "2026-08-18",
    acceloMilestoneId: "9002",
  },
  {
    id: "mstone3",
    projectId: "parkline-q3",
    title: "Direct mail drop",
    dueDate: "2026-08-20",
    acceloMilestoneId: "9003",
  },
];

export const activityEvents: ActivityEvent[] = [
  {
    id: "a1",
    projectId: "aster-house",
    actorId: "maya",
    verb: "posted",
    object: "Launch readiness — August 7",
    createdAt: "2026-08-07T14:20:00.000Z",
  },
  {
    id: "a2",
    projectId: "the-rowan",
    actorId: "alex",
    verb: "started",
    object: "Present identity directions",
    createdAt: "2026-08-07T13:12:00.000Z",
  },
  {
    id: "a3",
    projectId: "parkline-q3",
    actorId: "jordan",
    verb: "updated",
    object: "Launch paid social ad set",
    createdAt: "2026-08-07T12:18:00.000Z",
  },
  {
    id: "a4",
    projectId: "aster-house",
    actorId: "taylor",
    verb: "uploaded",
    object: "Exterior banner production specs",
    createdAt: "2026-08-07T10:42:00.000Z",
  },
];

export const currentProfile = profiles[0];

export function getProject(projectId: string) {
  return projects.find((project) => project.id === projectId);
}

export function getProfile(profileId?: string) {
  return profiles.find((profile) => profile.id === profileId);
}
